
server:
  port: 8888
mycar:
  price: 10000
  brand: BMWå®é©¬
debug: true
spring:
  mvc:
    hiddenmethod:
      filter:
        #### è¿™ä¸ªé»˜è®¤æ²¡å¼€å¯
        enabled: true
  banner:
    image:
      location: img.png
  resources:
#    static-locations: [classpath:/saeyon/] # å¦‚æœé…ç½®äº†è‡ªå®šä¹‰çš„èµ„æºè·¯å¾„,é‚£ä¹ˆå…¶ä»–è·¯å¾„å°±å¤±æ•ˆå•¦
    add-mappings: true
    cache:
      period: 12889
person:
  boss: false
  birth: 1994/06/12
  age: 27
  originPet:
    name: è‚¥è‚ 
    weight: 20.5
  interests:
    - "NBA 2K21"
    - "åŒäººåŒè¡Œ"
    - ç¯®çƒ
    - æ¸¸æˆ
    - Coding
  animal:
    - çŒ«
    - ğŸˆ
    - ç‹—
    - ğŸ°
  score:
    - æ•°å­¦: "æˆ‘çš„ä¸–ç•Œ ğŸ± ğŸ˜ ğŸ‡"
    - English:
        æœŸæœ«æµ‹éªŒ: 99
        æœŸä¸­æµ‹éªŒ: 99
    - Java:
        {name: å°é¸¡,weight: 150.11} # å¦‚æœå¾€ Object é‡Œé¢æ”¾å¯¹è±¡çš„è¯è¦ç”¨ èŠ±æ‹¬å· æ‹¬èµ·æ¥
#  salarys:
#    - 100.99
#    - 992222.200
#  allPets:
#    jq: #key å¦‚æœç”¨ä¸­æ–‡ä¼šæ— æ³•å±•ç¤ºè§£æ
#      - {name: å°é¸¡,weight: 150.11}
#      - {name: å°é¸­,weight: 200.25}
#    brdw: [{name: å°çŒ«,weight: 2000.00}]
  user-name: èµµæ—­é˜³
  salarys:



